version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    image: book_catalog:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sit722_part3_afoj_user:Ypry7RpbjBpsjBiUHY3Y3jmpJcFEdokT@dpg-crij5ou8ii6s73f4fi8g-a.singapore-postgres.render.com/sit722_part3_afoj
    depends_on:
      - postgres

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    image: inventory_management:latest
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://sit722_part3_afoj_user:Ypry7RpbjBpsjBiUHY3Y3jmpJcFEdokT@dpg-crij5ou8ii6s73f4fi8g-a.singapore-postgres.render.com/sit722_part3_afoj
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: sit722_part3_afoj_user
      POSTGRES_PASSWORD: Ypry7RpbjBpsjBiUHY3Y3jmpJcFEdokT
      POSTGRES_DB: sit722_part3_afoj
    ports:
      - "5432:5432"