apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sit72272p.azurecr.io/book_catalog:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_part3_afoj_user:Ypry7RpbjBpsjBiUHY3Y3jmpJcFEdokT@dpg-crij5ou8ii6s73f4fi8g-a.singapore-postgres.render.com/sit722_part3_afoj"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: sit72272p.azurecr.io/inventory_management:latest
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_part3_afoj_user:Ypry7RpbjBpsjBiUHY3Y3jmpJcFEdokT@dpg-crij5ou8ii6s73f4fi8g-a.singapore-postgres.render.com/sit722_part3_afoj"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
  type: LoadBalancer